name: System Builder

on:
  push:
    branches:
      - main

# permissions:
#   contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Zip Files
        working-directory: ./
        run: zip -r ./system.zip ./*

      - name: Get Version
        shell: bash
        id: get-version
        # run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"
        run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Cthulhu Dark v${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: "./system.zip, ./system.json"
          tag: ${{ steps.get-version.outputs.version }}
